blank_issues_enabled: false
contact_links:
  - name: Team
    url: mailto:team@codex.so
    about: Direct team contact.
  - name: Editor.js Telegram chat
    url: https://t.me/codex_editor
    about: Telegram chat for Editor.js users communication.
  - name: Editor.js contributors Telegram chat
    url: https://t.me/editorjsdev
    about: Telegram chat for Editor.js contributors communication.
